#docker-compose -f docker-compose.test.yml up -d --build
#docker-compose -f docker-compose.test.yml down -v

version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: microblog_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:
